logLevel: info

rtsp: true
rtspAddress: :8554

webrtc: true
webrtcAddress: :8889
webrtcEncryption: false
webrtcAllowOrigins: ["*"]
webrtcLocalUDPAddress: :8189
webrtcLocalTCPAddress: ""
webrtcIPsFromInterfaces: true
webrtcAdditionalHosts: []

paths:
  wardy:
    source: publisher
